#!/bin/sh

nft add table filter
nft add chain filter input \{ type filter hook input priority 0\; \}
nft add chain filter output \{ type filter hook output priority 0\; \}
nft add rule filter output skuid == 0 ct mark set 1
nft add rule filter input ct mark 1 log group 1337
nft add rule filter output ct mark 1 log group 1337

f="$(mktemp --suffix=.pcap)"
echo "Starting capture ..."
tcpdump --immediate-mode -Uni nflog:1337 -w "$f" &
sleep 2 # Give tcpdump some time to start
t=$!
echo "Running command ..."
# shellcheck disable=SC2068
$@
echo "Finalizing capture ..."
sleep 2
kill $t;
wireshark "$f"
